name: Build JNI Plugin

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [i686-unknown-linux-gnu, x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install rustup target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build Native
        run: cross build --release --target ${{ matrix.target }}
        working-directory: rust

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.target }}
          path: rust/target/${{ matrix.target }}/release/*.so

  build-windows-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [i686-pc-windows-msvc, x86_64-pc-windows-msvc]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install rustup target
        run: rustup target add ${{ matrix.target }}

      - name: Build Native
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: rust

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.target }}
          path: rust/target/${{ matrix.target }}/release/*.dll

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install rustup target
        run: rustup target add ${{ matrix.target }}

      - name: Build Native
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: rust

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.target }}
          path: rust/target/${{ matrix.target }}/release/*.dylib

  assemble-jar:
    needs: [build-linux, build-windows-msvc, build-macos]
    runs-on: ubuntu-latest
    env:
      DONT_COPY_NATIVES: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - run: mkdir -p src/main/resources

      - uses: actions/download-artifact@v4
        with:
          name: native-i686-unknown-linux-gnu
          path: src/main/resources/linux/x86
      - uses: actions/download-artifact@v4
        with:
          name: native-x86_64-unknown-linux-gnu
          path: src/main/resources/linux/amd64
      - uses: actions/download-artifact@v4
        with:
          name: native-aarch64-unknown-linux-gnu
          path: src/main/resources/linux/aarch64

      - uses: actions/download-artifact@v4
        with:
          name: native-i686-pc-windows-msvc
          path: src/main/resources/windows/x86
      - uses: actions/download-artifact@v4
        with:
          name: native-x86_64-pc-windows-msvc
          path: src/main/resources/windows/amd64

      - uses: actions/download-artifact@v4
        with:
          name: native-x86_64-apple-darwin
          path: src/main/resources/macos/amd64
      - uses: actions/download-artifact@v4
        with:
          name: native-aarch64-apple-darwin
          path: src/main/resources/macos/aarch64

      - name: List files
        run: |
          sudo apt update
          sudo apt install tree
          tree

      - name: Build Jar
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoReplaceBroken-artifact
          path: build/libs/*.jar